declare module 'mini-css-extract-plugin';
declare module 'html-webpack-plugin';
declare module 'html-webpack-externals-plugin';
declare module 'webpack-subresource-integrity';
declare module 'offline-webpack-plugin';
declare module 'clean-webpack-plugin';
declare module 'uglifyjs-webpack-plugin';
declare module 'string-replace-webpack-plugin';
declare module 'osenv';